version: 1.0.{build}

image: Visual Studio 2019

configuration: Release

platform:
  - x64

before_build:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build

artifacts:
  - path: dist
    name: popover-widget

deploy:
  provider: GitHub
  auth_token:
    secure: YOUR_GITHUB_TOKEN
  on:
    branch: main 